apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
   matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: app_release
          ports:
            - containerPort: 8000
          command: ["./bin/app", "foreground"]
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST
              value: "localhost"
            - name: SECRET_KEY_BASE
              value: "highlysecretkey"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
